{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
{{ include "labels" . | indent 4 }}
  name: {{ template "newrelic-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "newrelic-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "newrelic-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
