{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
{{ include "labels" . | indent 4 }}
  name: {{ template "newrelic-operator.fullname" . }}
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - newrelic.shanestarcher.com
  resources:
  - '*'
  - alertchannels
  - alertpolicies
  - dashboards
  - monitors
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
{{- end }}
