apiVersion: v1
kind: Secret
metadata:
  name: {{ template "newrelic-operator.fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  NEW_RELIC_APIKEY: {{ .Values.config.api_key | b64enc | quote }}
