{{- if and .Release.IsInstall }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitors.newrelic.shanestarcher.com
  annotations:
    "helm.sh/hook": crd-install
  labels:
{{ include "labels" . | indent 4 }}
spec:
  group: newrelic.shanestarcher.com
  names:
    kind: Monitor
    listKind: MonitorList
    plural: monitors
    singular: monitor
  scope: Namespaced
  version: v1alpha1
{{- end }}
