{{- if and .Release.IsInstall }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertchannels.newrelic.shanestarcher.com
  annotations:
    "helm.sh/hook": crd-install
  labels:
{{ include "labels" . | indent 4 }}
spec:
  group: newrelic.shanestarcher.com
  names:
    kind: AlertChannel
    listKind: AlertChannelList
    plural: alertchannels
    singular: alertchannel
  scope: Namespaced
  version: v1alpha1
{{- end }}
