{{- if .Values.customResources.alertChannels }}
{{- $top := . -}}
{{- range $name, $item := .Values.customResources.alertChannels }}
---
apiVersion: "newrelic.shanestarcher.com/v1alpha1"
kind: "AlertChannel"
metadata:
  name: {{ $name }}
  labels:
    {{- include "newrelic-operator.labels" $top | nindent 4 }}
spec:
{{ $item | toYaml | indent 2 }}
{{- end}}
{{- end}}
