apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "newrelic-operator.fullname" . }}
  labels:
    {{- include "newrelic-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "newrelic-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "newrelic-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "newrelic-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: OPERATOR_NAME
            value: {{ .Chart.Name }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: WATCH_NAMESPACE
          {{- if hasKey .Values "watchNamespace" }}
            value: {{ .Values.watchNamespace }}
          {{- else }}
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "newrelic-operator.fullname" . }}
          ports:
            - name: http
              containerPort: 60000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
