apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newrelic-operator.fullname" . }}
  labels:
{{ include "newrelic-operator.labels" . | nindent 4 }}
type: Opaque
data:
  NEW_RELIC_APIKEY: {{ .Values.config.api_key | b64enc | quote }}
