apiVersion: v1
kind: Secret
metadata:
  name: {{ template "newrelic-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "newrelic-operator.name" . }}
    helm.sh/chart: {{ include "newrelic-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  NEW_RELIC_APIKEY: {{ .Values.config.api_key | b64enc | quote }}
