kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    {{- include "newrelic-operator.labels" . | nindent 4 }}
  name: {{ include "newrelic-operator.fullname" . }}
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - newrelic.shanestarcher.com
  resources:
  - '*'
  - alertchannels
  - alertpolicies
  - dashboards
  - monitors
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
