{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "newrelic-operator.serviceAccountName" . }}
  labels:
{{ include "newrelic-operator.labels" . | nindent 4 }}
{{- end -}}
