apiVersion: apps/v1
kind: Deployment
metadata:
  name: newrelic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: newrelic-operator
  template:
    metadata:
      labels:
        name: newrelic-operator
    spec:
      serviceAccountName: newrelic-operator
      containers:
        - name: newrelic-operator
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - newrelic-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "newrelic-operator"
