apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitors.newrelic.shanestarcher.com
  labels:
    chart: sstarcher/newrelic-operator
spec:
  group: newrelic.shanestarcher.com
  names:
    kind: Monitor
    listKind: MonitorList
    plural: monitors
    singular: monitor
  scope: Namespaced
  version: v1alpha1
