apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertchannels.newrelic.shanestarcher.com
  labels:
    chart: sstarcher/newrelic-operator
spec:
  group: newrelic.shanestarcher.com
  names:
    kind: AlertChannel
    listKind: AlertChannelList
    plural: alertchannels
    singular: alertchannel
  scope: Namespaced
  version: v1alpha1
