apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertchannels.newrelic.shanestarcher.com
spec:
  group: newrelic.shanestarcher.com
  names:
    kind: AlertChannel
    listKind: AlertChannelList
    plural: alertchannels
    singular: alertchannel
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AlertChannel is the Schema for the alertchannels API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AlertChannelSpec defines the desired state of AlertChannel
          properties:
            configuration:
              additionalProperties:
                type: string
              type: object
            policies:
              items:
                type: string
              type: array
            type:
              description: TODO don't require setting of the type
              type: string
          type: object
        status:
          properties:
            hash:
              format: byte
              type: string
            id:
              type: string
            info:
              type: string
          type: object
      required:
      - metadata
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
